SELECT E2.ID, E2.GENOTYPE, E1.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA E1 JOIN ECOLI_DATA E2
WHERE E1.ID = E2.PARENT_ID
AND E1.GENOTYPE & E2.GENOTYPE = E1.GENOTYPE 
# 부모의 형질이랑 자식의 형질이 일치하고 그 형질이 부모의 형질이랑 일치할 때
ORDER BY ID